[package]
name = "rustpkg"
version = "0.1.0"
authors = ["Jon0 <Jono4728@gmail.com>"]

[dependencies]
nix = "0.12.0"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.7", features = ["serde", "v4"] }
